project:
  type: book

lang: de-CH

bibliography: refernzen.bib
csl: juristische_aufsaetze.csl

book:
  title: "PrWR 3cH (Schuljahr 2025/2026)"
  author: "Jacques Mock Schindler"
  date: today
  date-format: "D. MMMM YYYY"
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: "Unternehmensprojekt"
      chapters:
        - files/einfuehrung.qmd
        - files/auftrag.qmd
        - files/beurteilung.qmd
        - files/anleitung.qmd
    - part: "Die Eheschliessung"
      chapters:
        - files/eherecht/verloebnis.qmd
        - files/eherecht/eheschliessung.md
        - files/eherecht/trauung_im_ausland.md
        - files/eherecht/eheliche_gemeinschaft.md
    - part: "Das Güterrecht der Ehegatten"
      chapters:
        - files/eherecht/ordentlicher_gueterstand.md
        - files/eherecht/guetergemeinschaft.md
        - files/eherecht/guetertrennung.md
        
  repo-url: https://github.com/SkriptenMk/PRWR_cH_23-27
  repo-actions: [issue]

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    pdf-engine: lualatex
    documentclass: scrreprt
    papersize: a4
    lang: de-CH
    toc: true
    number-sections: true
    colorlinks: true