---
title: "Projekt IKT Weiterbildung für die Sek I"
---

Mit der hier dokumentierten Unterrichtseinheit sollen die Schülerinnen
und Schüler der HMS an der Kantonsschule Büelrain die Gelegenheit
erhalten, Praxiserfahrungen als Kaufleute zu sammeln. Vor diesem Hintergrund wurden
zwei Geschäftsleitungen etabliert, welche je ein Weiterbildungsangebot
in Sachen digitaler Hilfsmittel für die Sekundarschule Bülach entwickeln
und durchführen. 

Die Geschäftsleitungen wurden aufgrund der von den Schülerinnen und
Schülern in Gruppen erarbeiteten Business Model Canvas gebildet. Die
beiden Gruppen mit den überzeugendsten Modellen wurden mit der Aufgabe
der Geschäftsleitung betraut. Die anderen Schülerinnen und Schüler
wurden gleichmässig den beiden Geschäftsleitungen als Mitarbeiter
zugeteilt. 

Aktuell arbeiten die beiden Teams unter der Führung der
Geschäftsleitungen an an der Vorbereitung der geplanten
Weiterbildungsangebote. Ziel dieser Sequenz ist es, dass die geplanten
Angebote nach den Sommerferien 2025 der Schulleitung der Sekundarschule
Bülach im Sinne einer Offerte präsentiert werden können.