---
title: "Projektauftrag"
---

## Orientierung

Im Quartal zwischen Frühlings- und Sommerferien 2025 geht es darum, dass
die beiden Teams unter der Führung ihrer jeweiligen Geschäftsleitung die
geplanten Weiterbildungsangebote soweit ausarbeiten, dass sie der
Schulleitung der Sekundaschule Bülach präsentiert werden können.

## Absicht

Ich will, dass alle Schülerinnen und Schüler einen Beitrag zum Gelingen
der Weiterbildung leisten. Ausserdem will ich, dass die Schülerinnen der
beiden Geschäftsleitungen die Gelegenheit erhalten, Verantwortung zu
übernehmen und Führungserfahrung zu sammeln.

## Auftrag

Die Geschäftsleitungen stellen sicher, dass in der zweiten Woche
nach den Sommerferien 2025 ein Team für die Präsentation der
Weiterbildungsangebote bereit steht.

## Besondere Anordnungen

* Der Zeitkredit für die Präsentation beträgt 10 Minuten (exklusive Fragen).
* In der zweiten Woche nach den Sommerferien findet ein Probelauf der
  Präsentation statt.
* Die Geschäftsleitungen sind verantwortlich, dass mein Stellvertreter
  nach jeder Lektion schriftlich über den Stand der Arbeiten ins Bild
  gesetzt wird. Das Reporting umfasst die folgenden Punkte:
  * Was wurde in der Lektion erreicht?
  * Was steht als nächstes an?
  * Wo gibt es Probleme?
* Die Vorbereitungen sind so weit voranzutreiben, dass die Umsetzung des
  Weiterbildungsangebots unmittelbar nach der Präsentation beginnen
  kann.
  
## Erreichbarkeit

Sie erreichen meinen Stellvertreter über das PRWR Teams.