---
title: "Das Verlöbnis"
author: "Jacques Mock Schindler"
date: 2026-03-13
date-format: "DD. MMMM YYYY"
lang: de-CH
---

Die Verlobung ist das Versprechen des Brautpaares, miteinander die Ehe
einzugehen. Obwohl es sich bei der Verlobung um ein Vertrag handelt
(vgl. [Marginalie von Art. 90 ZGB des französischen
Textes](https://www.fedlex.admin.ch/eli/cc/24/233_245_233/fr#book_2/part_1/tit_3/chap_1/lvl_A)),
gibt es nach Art. 90 Abs. 3 ZGB keinen klagbaren Anspruch auf das Eingehen der Ehe.

Wie für alle Rechtsgeschäfte gilt, dass die Verlobten grundsätzlich
volljährig sein müssen. Allerdings lässt 
[Art. 90 Abs. 2
ZGB](https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_90)
ein Verlöbnis Minderjähriger mit der Zustimmung der gesetzlichen Vertreter
zu. Voraussetzung ist lediglich die Urteilsfähigkeit des unmündigen
Verlobten in Bezug auf die Folgen des Verlöbnisses[@art90zgb, N 16].

Auch wenn das Verlöbnis heute keine allzu grosse praktische Bedeutung
mehr hat[@familienrecht_zgb, N 04.01], entfaltete es doch vor allem im
Zusammenhang mit seiner Auflösung rechtliche Konsequenzen. Dann sind
nämlich Geschenke und Auslagen, welche im Hinblick auf die
Eheschliessung getätigt wurden, zurückzuerstatten.

[Art. 91
ZGB](https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_91)
spricht allgemein von Geschenken. Damit sind jedoch nicht nur
Schenkungen i. S. v. [Art. 239
OR](https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_239),
sondern alle unentgeltlichen Zuwendungen gemeint[@art90zgb, N 5].
Ausserdem sind nach [Art. 92
ZGB](https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_92) die im
Hinblick auf den Eheschluss gemachten Aufwendungen angemessen zu
entschädigen. 




